dataset_jsonl_path: /path/to/jsonl/file.jsonl
data:
  database_insert_batch_size: 100
  remove_duplicates: true
semantic_index:
  embeddings_model_name: sdadas/st-polish-paraphrase-from-distilroberta
  embeddings_computation_batch_size: 3
  metric: cos
  connectivity: 128
  dtype: 'f32'
  expansion_add: 128
  expansion_search: 256
  n_clusters: 10000
features:
  basic: true
  reranker:
    model_name: sdadas/polish-reranker-base-ranknet
    batch_size: 16
    strategy: truncate
  language_tool: false
